# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-22 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='startup_team',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='startup_team_condition',
        ),
    ]
