# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-22 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0002_auto_20180322_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='startup_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
