# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-23 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0006_startup_startup_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='startup_company',
            field=models.CharField(default='cp name', max_length=100),
        ),
    ]
