# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-22 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0003_auto_20180322_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='startup_date',
            field=models.CharField(default='format = dd/mm/yyyy', max_length=20),
        ),
    ]
