# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-22 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0004_auto_20180322_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('project_name', models.CharField(max_length=30)),
                ('project_description', models.TextField(max_length=2500)),
                ('skill_required', models.CharField(max_length=200)),
                ('team_size', models.IntegerField(default=6)),
            ],
        ),
    ]
