# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-25 17:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('address', models.CharField(max_length=150)),
                ('locality', models.CharField(max_length=30)),
                ('state', models.CharField(default='Enter State', max_length=30)),
                ('postal_code_4', models.PositiveIntegerField(null=True)),
                ('user_type', models.CharField(choices=[('s', 'Entrepreneur'), ('c', 'Mentor'), ('d', 'Investor'), ('v', 'Job Seeker')], max_length=1)),
                ('skill_sets', models.CharField(default='Example:Computer Literacy/Information Technology/Business Experties', max_length=150)),
                ('activation_key', models.CharField(default=uuid.UUID('8b100980-304f-11e8-a2be-9840bb29ab05'), max_length=64, verbose_name='Activation key')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
