# Generated by Django 2.0.2 on 2018-03-28 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0005_auto_20180328_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=uuid.UUID('c98f2cb8-32ae-11e8-8758-94e979bba598'), max_length=64, verbose_name='Activation key'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('Entrepreneur', 'Entrepreneur'), ('Mentor', 'Mentor'), ('Investor', 'Investor'), ('Job seeker', 'Job Seeker')], max_length=1),
        ),
    ]
