# Generated by Django 2.0.2 on 2018-03-29 07:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0008_auto_20180329_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=uuid.UUID('d3538324-3325-11e8-8c8d-94e979bba598'), max_length=64, verbose_name='Activation key'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('Entrepreneur', 'Entrepreneur'), ('Mentor', 'Mentor'), ('Investor', 'Investor'), ('Job seeker', 'Job Seeker')], max_length=20),
        ),
    ]
