# Generated by Django 2.0.2 on 2018-03-30 05:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0010_auto_20180329_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=uuid.UUID('680a3d48-33d7-11e8-af16-94e979bba598'), max_length=64, verbose_name='Activation key'),
        ),
    ]
