# Generated by Django 2.0.2 on 2018-03-30 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0012_auto_20180330_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=uuid.UUID('b6e09ab4-344c-11e8-b14b-94e979bba598'), max_length=64, verbose_name='Activation key'),
        ),
    ]
