# Generated by Django 2.0.2 on 2018-03-30 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0013_auto_20180331_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=uuid.UUID('ced0c84a-344c-11e8-bd19-94e979bba598'), max_length=64, verbose_name='Activation key'),
        ),
    ]
