# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-26 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=uuid.UUID('37de14ca-30bc-11e8-9e6a-9840bb29ab05'), max_length=64, verbose_name='Activation key'),
        ),
    ]
