# Generated by Django 2.0.2 on 2018-03-29 07:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0007_auto_20180328_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=uuid.UUID('3636259c-3325-11e8-a7bb-94e979bba598'), max_length=64, verbose_name='Activation key'),
        ),
    ]
