# Generated by Django 2.0.2 on 2018-03-29 07:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0009_auto_20180329_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_photo',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=uuid.UUID('8161d082-3326-11e8-afd4-94e979bba598'), max_length=64, verbose_name='Activation key'),
        ),
    ]
