# Generated by Django 2.0.2 on 2018-03-30 09:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0011_auto_20180330_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=uuid.UUID('706a3754-3400-11e8-9f0d-94e979bba598'), max_length=64, verbose_name='Activation key'),
        ),
    ]
