# Generated by Django 2.0.2 on 2018-03-31 03:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0015_auto_20180331_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=uuid.UUID('4bf0be70-3490-11e8-9ecf-94e979bba598'), max_length=64, verbose_name='Activation key'),
        ),
    ]
