# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 05:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incubator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incubator_name', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=30)),
                ('city_location', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=2500)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('logo', models.CharField(max_length=30)),
                ('picture', models.CharField(max_length=30)),
            ],
        ),
    ]
