# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_incubators_varify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incubators',
            name='logo',
            field=models.FileField(upload_to=''),
        ),
    ]
