# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-24 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('designation', models.CharField(default='CEO/CFO at XYZ', max_length=20)),
                ('expertise', models.CharField(default='Buisness Development, Content etc.', max_length=30)),
                ('description', models.TextField(default='Give a brief about yourself', max_length='1000')),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
