# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-24 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentors',
        ),
    ]
