# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-24 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_mentors'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
