# Generated by Django 2.0.2 on 2018-03-30 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enetwork', '0002_auto_20180331_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
