# Generated by Django 2.0.2 on 2018-03-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enetwork', '0004_auto_20180331_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='problem_category',
            field=models.CharField(choices=[('Technical/software', 'Technical/software'), ('Government Ministry', 'Government Ministry'), ('Hardware', 'Hardware'), ('Business', 'Business'), ('Management', 'management')], max_length=50),
        ),
    ]
