# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incubator',
            new_name='Incubators',
        ),
    ]
