# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-11 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180307_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inc_img', models.FileField(upload_to='')),
                ('inc_details', models.TextField(max_length=False)),
                ('inc_doc', models.FileField(upload_to='')),
                ('inc_policy', models.FileField(upload_to='')),
                ('incubator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Incubators')),
            ],
        ),
    ]
