# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-11 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incubators',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='incubators',
            name='rating',
        ),
    ]
