# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-11 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180312_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='inc_details',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='details',
            name='inc_doc',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='details',
            name='inc_policy',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
