# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-11 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180312_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='inc_name',
            field=models.CharField(default='Incubator name', max_length=30),
            preserve_default=False,
        ),
    ]
