# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_details_inc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubators',
            name='varify',
            field=models.BooleanField(default=False),
        ),
    ]
