# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-15 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180313_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='inc_contact',
            field=models.CharField(default='Enter all available means of contacting', max_length=600),
        ),
    ]
