# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-15 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180316_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='incubator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banana_pudding', to='main.Incubators'),
        ),
    ]
