# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-20 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_startup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Startup',
        ),
    ]
