# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-26 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_startup'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubators',
            name='latt',
            field=models.FloatField(default=30),
        ),
        migrations.AddField(
            model_name='incubators',
            name='lonn',
            field=models.FloatField(default=25),
        ),
    ]
